server:
  port: 8080

spring:
  application:
    name: policy-service
  datasource:
    url: jdbc:postgresql://localhost:5432/policydb
    username: itau
    password: itau
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate.format_sql: true
      hibernate.jdbc.time_zone: UTC
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

fraud:
  api:
    base-url: http://localhost:8081
    connect-timeout: 2s
    read-timeout: 5s

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: when_authorized
